"""Render the MENACE mini-paper as a polished five-page PDF."""
from pathlib import Path
import csv
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image, Table, TableStyle

OUT = Path("paper/menace_research_paper.pdf")
BLUE = colors.HexColor("#1F4E79")

def footer(canvas, doc):
    canvas.saveState(); canvas.setFont("Helvetica", 8); canvas.setFillColor(colors.HexColor("#666666"))
    canvas.drawString(0.65*inch, 0.42*inch, "MENACE Controlled Experiments")
    canvas.drawRightString(7.85*inch, 0.42*inch, str(doc.page)); canvas.restoreState()

def p(text, style): return Paragraph(text, style)

def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.2, leading=12.1, spaceAfter=6)
    title = ParagraphStyle("Title2", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=20, leading=23, textColor=BLUE, alignment=TA_CENTER, spaceAfter=10)
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=13, leading=15, textColor=BLUE, spaceBefore=5, spaceAfter=5)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=10.5, leading=13, textColor=BLUE, spaceBefore=4, spaceAfter=3)
    small = ParagraphStyle("Small", parent=body, fontSize=7.7, leading=9.6)
    doc = SimpleDocTemplate(str(OUT), pagesize=letter, rightMargin=.65*inch, leftMargin=.65*inch, topMargin=.6*inch, bottomMargin=.62*inch)
    story=[]
    story += [Spacer(1,.2*inch), p("From Demonstration to Experiment:<br/>Controlled Ablations of MENACE Learning", title), p("<b>Hayden Ng</b> &nbsp;&nbsp;|&nbsp;&nbsp; September 2026", ParagraphStyle("Author", parent=body, alignment=TA_CENTER)), Spacer(1,.15*inch)]
    story += [p("Abstract", h1), p("MENACE is an early reinforcement-learning system that represents tic-tac-toe states as matchboxes and actions as colored beads. Prior demonstrations typically show that a single agent improves over one long run, but do not isolate which design choices cause improvement or quantify variability between runs. This study asks how reward structure, explicit exploration, symmetry reduction, training opponent, and matchbox initialization affect MENACE learning. Eleven controlled conditions were evaluated across 100 independently seeded trials each. Every trial used 3,000 training games and a held-out random-opponent benchmark. Symmetry reduction increased mean win rate from <b>70.23% to 80.30%</b> and reduced the learned state space from <b>2,118.0 to 336.6</b> matchboxes. A stronger loss penalty achieved the highest win rate (85.10%), while excessive initial beads and added epsilon exploration reduced performance.", body)]
    story += [p("1. Introduction", h1), p("Donald Michie's Matchbox Educable Noughts and Crosses Engine (MENACE) illustrates learning through reward and punishment. For each board state, a matchbox stores beads corresponding to legal moves. A move is sampled in proportion to its bead count; beads associated with the completed game are reinforced or removed according to the outcome.", body), p("A working implementation establishes that learning can occur, but a research claim requires controlled comparisons, repeated independent runs, uncertainty estimates, and definitions chosen before inspecting outcomes. The research question is: <b>How do reward structure, explicit exploration, symmetry reduction, training opponent, and initialization affect final performance, convergence, memory use, and policy stability?</b>", body), p("The central hypothesis was that symmetry reduction would improve sample efficiency and reduce memory without restricting the best policy. Secondary hypotheses were that stronger negative feedback would suppress losing actions more quickly, moderate exploration might avoid premature concentration, and large uniform initial bead counts would slow adaptation.", body)]
    story += [PageBreak(), p("2. Background", h1), p("In reinforcement-learning terminology, the board is the <b>state</b>, an empty square is an <b>action</b>, and the win/draw/loss update is the <b>reward signal</b>. MENACE does not estimate a value function explicitly. Each bead count is a nonnegative action preference. If action a has bead count b(a) in state s, its selection probability is b(a) divided by the sum across legal actions. A one-bead floor prevents permanent action elimination.", body), p("Tic-tac-toe has geometric redundancy. Rotating or reflecting a board does not change its strategic meaning. Canonicalization maps all eight rotations and reflections to one representative state and maps the chosen action back to the original orientation. This shares experience across equivalent observations.", body)]
    story += [p("3. Methodology", h1), p("The baseline used three initial beads per action, win/draw/loss updates of +3/+1/-1, bead-proportional sampling, symmetry reduction, and a random training opponent. Ten treatments each changed one factor: three reward variants, two epsilon-exploration levels, symmetry disabled, self-play, minimax training, and initial bead counts of one or ten.", body), p("Each condition used <b>100 independent trials</b>. Seeds were deterministic and recorded; training and evaluation used separate random streams. Every trial trained MENACE as X for 3,000 games. At 300-game checkpoints, the frozen policy played 200 validation games against a separately seeded random opponent. Final held-out evaluation used 400 games. Evaluation changed neither matchboxes nor the training random-number state.", body), p("Outcomes were final win/draw/loss rate; sample variance and 95% confidence interval across trials; games to convergence; state-space size; and policy stability. Validation score was win rate + 0.5 x draw rate. Convergence was the first checkpoint after which score never fell more than 0.05 below its final value. Policy stability was the fraction of shared states whose deterministic greedy action was unchanged between the final two checkpoints.", body)]
    story += [p("Experimental controls", h2), p("All conditions used the same game engine, X position, training budget, checkpoint schedule, evaluation opponent class, evaluation budget, and seed-construction scheme. Treatment names, parameters, metric definitions, and base seed are stored in results/metadata.json. Trial-level output is retained rather than only aggregate statistics.", body)]
    with open("results/summary.csv") as f: rows=list(csv.DictReader(f))
    data=[["Condition","Win %","Draw %","Conv.","States","Stable %"]]
    for r in rows:
        data.append([r["condition"].replace("_"," "), f'{100*float(r["mean_win_rate"]):.2f}', f'{100*float(r["mean_draw_rate"]):.2f}', f'{float(r["mean_games_to_convergence"]):.0f}', f'{float(r["mean_state_space_size"]):.1f}', f'{100*float(r["mean_policy_stability"]):.1f}'])
    table=Table(data, colWidths=[2.0*inch,.58*inch,.58*inch,.58*inch,.58*inch,.62*inch], repeatRows=1)
    table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),BLUE),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTNAME",(0,1),(-1,-1),"Helvetica"),("FONTSIZE",(0,0),(-1,-1),7.4),("GRID",(0,0),(-1,-1),.25,colors.HexColor("#BBBBBB")),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#EEF3F8")]),("ALIGN",(1,1),(-1,-1),"RIGHT"),("VALIGN",(0,0),(-1,-1),"MIDDLE")]))
    story += [PageBreak(), p("4. Results", h1), table, Spacer(1,6), Image("results/figures/condition_win_rates.png", width=7.05*inch, height=3.52*inch), p("Figure 1. Final held-out win rate against a random opponent. Error bars are 95% confidence intervals across 100 independently trained agents.", small)]
    story += [PageBreak(), p("5. Symmetry Ablation", h1), Image("results/figures/symmetry_ablation.png", width=7.05*inch, height=2.05*inch), p("Figure 2. Removing symmetry changes performance, representation size, convergence, and stability while all other factors remain fixed.", small), p("Disabling symmetry reduced mean win rate by <b>10.07 percentage points</b>, from 80.30% to 70.23%; the 95% confidence intervals did not overlap. Mean state-space size increased from 336.6 to 2,118.0 matchboxes, a 6.29-fold increase. Canonicalization therefore reduced stored states by <b>84.1%</b>.", body), p("The ablation supports two mechanisms. First, symmetry saves memory by merging equivalent boards. Second, each update generalizes to rotated and reflected boards, so every canonical matchbox receives more relevant experience. Without reduction, a fixed training budget is spread across redundant states. Eventual performance might become similar with much more training, but symmetry materially improves sample efficiency here.", body), p("Convergence must be interpreted with final performance: symmetry-off convergence was 1,698 games, slightly faster than baseline's 1,743, because the definition is relative to each condition's own final score. Likewise, policy stability was almost unchanged (95.7% versus 95.6%); a stable policy can be stably inferior.", body), p("6. Discussion", h1), p("Reward design had a clear effect. The harsh-loss condition achieved the best win rate, 85.10%, and converged in 1,599 games. Stronger punishment appears to remove probability mass from losing trajectories faster. Added epsilon exploration hurt: values of 0.10 and 0.30 reduced win rate to 78.94% and 77.48%. MENACE already explores through bead-weighted sampling, so epsilon partially ignores learned preferences.", body), p("Self-play slightly exceeded baseline at 81.68%. Minimax training reached only 60.75% against random. Perfect play visits a narrow set of responses, whereas random play induces different states; the result illustrates training-evaluation distribution shift. Ten initial beads also slowed adaptation because more updates are required to move probabilities away from a uniform prior.", body)]
    story += [PageBreak(), p("7. Limitations", h1), p("Tic-tac-toe is tiny, deterministic, fully observable, and solved, so results should not be generalized directly to modern reinforcement learning. MENACE is tabular rather than a function approximator. Only the X role, a 3,000-game budget, and a random final opponent were studied. Confidence intervals quantify seed-to-seed variation but do not remove bias from the selected environment, metrics, or treatment grid. Convergence is relative to final performance, not time to optimality. Multiple comparisons were exploratory and no family-wise correction was applied.", body), p("8. Future Work", h1), p("Future work should use longer horizons to distinguish delayed from permanently weaker conditions, repeat treatments with MENACE as O, and evaluate against mixtures of random, heuristic, self-play, and minimax opponents. A factorial design could test interactions, particularly symmetry by initialization and reward by opponent. Bootstrap intervals and time-to-fixed-threshold analysis would strengthen inference. Finally, MENACE can be compared with Q-learning and Monte Carlo control under matched representations and sample budgets.", body), p("Reproducibility", h1), p("The repository contains 1,100 trial-level observations, aggregate tables, metadata, figures, source code, and automated tests. The command in RESEARCH.md reconstructs the full experiment with base seed 20260910. Evaluation is isolated from training and does not update matchboxes or consume the training random stream.", body), p("References", h1), p("1. Michie, D. (1961). Trial and error. <i>Science Survey</i>, Part 2, 129-145.<br/>2. Michie, D., and Chambers, R. A. (1968). BOXES: An experiment in adaptive control. <i>Machine Intelligence 2</i>, 137-152.<br/>3. Sutton, R. S., and Barto, A. G. (2018). <i>Reinforcement Learning: An Introduction</i> (2nd ed.). MIT Press.", body), Spacer(1,.15*inch), p("Research pipeline", h2), p("question -> hypothesis -> controlled conditions -> independent trials -> held-out evaluation -> uncertainty -> interpretation", ParagraphStyle("Pipeline", parent=body, alignment=TA_CENTER, textColor=BLUE, fontName="Helvetica-Bold"))]
    doc.build(story, onFirstPage=footer, onLaterPages=footer)

if __name__ == "__main__": main()
